# Section - Numpy 

## Course goals

- numpy, create arrays with numpy
- retrive information from numpy => slicing and indexing
- basic numpy operations

### Numpy - 
- used for creating n-dimensional array
- much efficient than python lists

In [1]:
import numpy as np
# numpy arrays 
# transforming standard list
# built-in funciutons
# generating random numbers


In [2]:
arr = [1,2,4,5,6,7]
type(arr)

list

In [3]:
# size of normal python array
len(arr)

6

In [4]:
arr1 = np.array(arr)
arr1

array([1, 2, 4, 5, 6, 7])

In [5]:
# size of numpy array
arr1.size

6

In [6]:
type(arr1)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3],[4,5,6], [7,8,9]]
type(my_matrix)

list

In [8]:
matrix2 = np.array(my_matrix)
matrix2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
type(matrix2)

numpy.ndarray

In [10]:
# arange is simlar to range() function in python
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
# 2-dimensional array with all zeros
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
# linearly spaced - from start to stop give back 3(n) evenly spaced number
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
# create identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
# create random distribution of data

In [17]:
np.random.rand(3,2)

array([[0.51974717, 0.68214391],
       [0.17762191, 0.14571372],
       [0.16007627, 0.86707477]])

In [18]:
# create samples from standard normal distribution
np.random.randn(2,3)

array([[ 1.0487375 , -1.05883929, -1.11100994],
       [-0.24736541,  0.40963371,  2.00127523]])

In [19]:
# generate array of n random integers from start to stop
# np.random.randint(start,stop,size(n))
np.random.randint(0,10,4)
# from 0 to 10 generate array of 4 elements --random numbers

array([9, 1, 4, 4])

In [20]:
np.random.seed(42) # allows to produce a particular set of random numbers
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [21]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
ranarr = np.random.randint(0,101,10)

In [24]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [25]:
ranarr.max()

99

In [26]:
ranarr.min()

2

In [27]:
ranarr.argmax()

5

In [28]:
ranarr.argmin()

7

In [29]:
ranarr.dtype

dtype('int64')

In [30]:
arr.shape

(25,)

In [31]:
arr=arr.reshape(5,5)

In [32]:
arr.shape

(5, 5)

## Indexing and selection

In [33]:
arr = np.arange(0,10)

In [34]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[8]

8

In [36]:
arr[1:5]

array([1, 2, 3, 4])

In [37]:
arr[0:6:2]

array([0, 2, 4])

In [38]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [39]:
arr[5::2]

array([5, 7, 9])

In [40]:
# Broadcasting

In [41]:
arr[0:5] = 100

In [42]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [43]:
arr = np.arange(0,11)

In [44]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [45]:
slice_of_arr[:] = 99

In [46]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [47]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [48]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [49]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
arr_2d[0][1]

10

In [51]:
arr_2d.shape

(3, 3)

In [52]:
# conditional selection

In [53]:
arr = np.arange(1,11)

In [54]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [56]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [57]:
arr[arr>3].size

7

## Numpy Operations

In [58]:
arr = np.arange(0,10)

In [59]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr+5 # add 5 to every element

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
# arr must be of same shape
# 2 arrays will be added
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [64]:
1/arr

/tmp/ipykernel_45816/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [65]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [66]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [67]:
np.log(arr)

/tmp/ipykernel_45816/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [68]:
# summary statistics

In [69]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr.sum()

45

In [71]:
arr.mean()

4.5

In [72]:
arr.max()

9

In [73]:
arr.var()

8.25

In [74]:
arr.std()

2.8722813232690143

In [80]:
arr_2d = np.arange(0,25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [81]:
arr_2d.sum()

300

In [82]:
arr_2d.sum(axis=0) #across the row

array([50, 55, 60, 65, 70])

In [84]:
arr_2d.sum(axis=1) # across the column

array([ 10,  35,  60,  85, 110])